[package]
name = "seekslam_onnx"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "(WIP)使用nalgebra(纯rust)实现的onnx opset 22运行时"
keywords = ["onnx", "rust", "nalgebra", "opset22", "runtime"]

[dependencies]
# 线性代数
nalgebra.workspace = true
# 随机数
rand.workspace = true
# 错误处理
anyhow.workspace = true